version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --configuration production

artifacts:
  files:
    - '**/*'
  base-directory: dist/my-angular-cicd
